# Logging settings:
loglevel: 'INFO'6
logging_dir: 'logs'
log_to_neptune: False
neptune_username: '<neptune.ai username>'
neptune_project_name: '<neptune.ai project_name>'
neptune_api_token: '<neptune.ai API token>'

# Train/test dataset and devkit location
stanford_raw_data_path: '<path to the folder containing: car_ims.tgz, cars_annos.mat, car_devkit.tgz>'
stanford_data_path: 'input/stanford'

# Network and training settings
architecture: 'sq_10'  # Possible options in `models.arch_dict`
batch_size: 32
validate_on_test: False
split_ratios: [0.8, 0.2]  # Train/valid ratios - if `validate_on_test==False`
num_epochs: 3

# Optimizer settings
optimizer: 'adam'  # possible choices: 'adam', 'sgd'
learning_rate: 1e-3

# Output settings
output_path: 'output'

# Other settings
seed: 42
