# Logging settings:
loglevel: 'INFO'
logging_dir: 'logs'
log_to_neptune: False
neptune_username: '<neptune.ai username>'
neptune_project_name: '<neptune.ai project name>'
neptune_api_token: '<neptune.ai API token>'

# Train/test dataset and devkit location
stanford_raw_data_path: '<path to the folder containing: car_ims.tgz, cars_annos.mat, car_devkit.tgz>'
stanford_data_path: 'input/stanford'

# Preprocessinng settings
image_size: [227, 227]
convert_to_grayscale: False
normalize: True  
normalization_params_rgb:  # Applied when 'convert_to_grayscale==False'
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]
normalization_params_grayscale:  # Applied when 'convert_to_grayscale==True'
  mean: [0.5]
  std: [0.5]

# Network and training settings
architecture: 'sq_10'  # Possible options in 'models.arch_dict'
batch_size: 16
validate_on_test: False
split_ratios: [0.8, 0.2]  # Train/valid ratios - if 'validate_on_test==False'
num_epochs: 100

# Optimizer settings
optimizer: 'adam'  # possible choices: 'adam', 'sgd'
learning_rate: 0.001

# Output settings
output_path: 'output'

# Other settings
seed: 42
