# Logging settings:
loglevel: 'INFO'
logging_dir: 'logs'

# Train/test dataset and devkit location
stanford_raw_data_path: '<path to the folder containing: car_ims.tgz, cars_annos.mat, car_devkit.tgz>'
stanford_data_path: 'input/stanford'

# Network and training settings
architecture: 'sq_10'  # Possible options in `models.arch_dict`
batch_size: 32
split_ratios: [0.8, 0.2]  # Train/valid ratios
num_epochs: 1
seed: 42

# Optimizer settings
optimizer: 'adam'  # possible choices: 'adam', 'sgd'
learning_rate: 1e-3

# Output settings
output_path: 'output'
