# Train/test dataset and devkit location
stanford_raw_data_path: '<path to the folder containing: car_ims.tgz, cars_annos.mat, car_devkit.tgz>'
stanford_data_path: 'input/stanford'

# Logging settings:
loglevel: 'INFO'
logging_dir: 'logs'